version: '2.24.6'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
